WIP: LCAM 1540 Solicitors Costs Not Record on Database When Creating Hardship
ministryofjustice/laa-crime-hardship pull request #102
Opened 2024-08-29 14:21 UTC by nigelpain

## What

[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1540)

Describe what you did and why.

## Checklist

Before you ask people to review this PR:

- [ ] Tests should be passing: `./gradlew test`
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase main`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

2024-09-03 13:57 UTC, venkat980 requested changes

2024-09-03 13:57 UTC, venkat980 commented on crime-hardship/build.gradle
> +        commonsModSchemas           : "1.8.2-SNAPSHOT",
Can you please merge the common schemas and use the main version instead of snapshot?

2024-09-04 08:10 UTC, nigelpain commented on crime-hardship/build.gradle
> +        commonsModSchemas           : "1.8.2-SNAPSHOT",
Commons changes have been merged and version updated now.

2024-09-04 08:34 UTC, venkat980 approved these changes

2024-09-04 12:21 UTC, merged