[WIP]LCAM-1609|Replace WebClient with Declarative HTTP Interface
ministryofjustice/laa-crime-hardship pull request #111
Opened 2024-10-24 22:44 UTC by venkat980

## What

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1609)

Refactored the service to use Declarative HTTP Interface instead of WebClient.
Using resillience4j for retry mechanism.

TODO: Move the ErrorDTO and TraceIdHandler classes to a new common-client jar.

## Checklist

Before you ask people to review this PR:

- [ ] Tests should be passing: `./gradlew test`
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase main`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

## Additional checks

- Don’t forget to [run](https://github.com/ministryofjustice/laa-crimeapps-maat-functional-tests/actions/workflows/ExecuteUiTests.yaml) the MAAT functional test suite after deploying your changes to the DEV or TEST environments to ensure your changes haven’t broken any of the functional tests.

2024-11-12 14:05 UTC, Mhowell494 requested changes

2024-11-12 14:05 UTC, Mhowell494 commented on crime-hardship/src/test/java/uk/gov/justice/laa/crime/hardship/service/MaatCourtDataServiceTest.java
> +        verify(maatCourtDataClient, times(1)).getHardship(HARDSHIP_ID);
I don't think the tests in this class are adding much value. `maatCourtDataService.getHardship(HARDSHIP_ID)` is called, but since there’s no stub set up for maatCourtDataClient.getHardship, it always returns null (the default for unmocked methods returning non-void types). Personally, I would add the stubs back in.

2024-11-12 14:05 UTC, Mhowell494 commented on crime-hardship/src/test/java/uk/gov/justice/laa/crime/hardship/integration/HardshipIntegrationTest.java
> -
Why have we removed this and the other authorisation tests?

2024-11-12 14:17 UTC, venkat980 commented on crime-hardship/src/main/java/uk/gov/justice/laa/crime/hardship/exception/HardshipExceptionHandler.java
> +        } catch (Exception ex) {
We want to make sure we pass any error messages thrown from the downstream. Currently we are using ErrorDTO across all the mod services including the MAAT API.

2024-11-13 18:49 UTC, venkat980 commented on crime-hardship/docker-compose.local.yml
> +      - MAAT_API_BASE_URL=http://court-data-api:8090/api/internal/v1/assessment
I agree, we need to streamline the endpoints in MAAT Court Data API :-)

2024-11-14 23:12 UTC, venkat980 commented on crime-hardship/src/test/java/uk/gov/justice/laa/crime/hardship/service/MaatCourtDataServiceTest.java
> +        verify(maatCourtDataClient, times(1)).getHardship(HARDSHIP_ID);
That was an unintentional removal of stubbing, added the stubs back.

2024-11-14 23:13 UTC, venkat980 commented on crime-hardship/src/test/java/uk/gov/justice/laa/crime/hardship/service/CrimeMeansAssessmentServiceTest.java
> +        verify(cmaApiClient, times(1)).find(anyString());
Updated the test to remove the verify call.

2024-11-14 23:14 UTC, venkat980 commented on crime-hardship/src/test/java/uk/gov/justice/laa/crime/hardship/integration/HardshipIntegrationTest.java
> -
Added the authorisation tests back.

2024-11-18 13:13 UTC, venkat980 commented on crime-hardship/src/main/java/uk/gov/justice/laa/crime/hardship/exception/HardshipExceptionHandler.java
> +        } catch (Exception ex) {
Updated.

2024-11-18 13:13 UTC, venkat980 commented on crime-hardship/src/main/java/uk/gov/justice/laa/crime/hardship/config/WebClientsConfiguration.java
> +                .filter(oauth)
Updated.

2024-11-18 17:23 UTC, Mhowell494 approved these changes

2024-11-18 18:57 UTC, merged