LCAM-891
ministryofjustice/laa-crime-hardship pull request #40
Opened 2023-09-11 11:57 UTC by Mhowell494

## What

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-891)

- New CRUD endpoints
- Mapper interfaces and implementations for converting between the MAAT and Hardship data models.
- Refined schemas and improved naming conventions
- Deleted unused classes and schemas.
- Fixed failing test cases and added new scenarios.

2023-09-11 12:38 UTC, Mhowell494 commented
The code smells in the SonarCloud report are either false positives or issues that will be fixed when the controllers are wired up in the future.

The code coverage is a little low as there are no Controller tests at the moment. However, this will be addressed as part of a future ticket.

2023-09-14 11:34 UTC, venkat980 requested changes

2023-09-14 11:42 UTC, Mhowell494 commented on crime-hardship/src/main/java/uk/gov/justice/laa/crime/hardship/service/HardshipService.java
> +                .map(item -> {
Good suggestion, I'm changed it to make use of the `filter` function now.

2023-09-14 11:46 UTC, Mhowell494 commented on crime-hardship/src/main/java/uk/gov/justice/laa/crime/hardship/service/HardshipService.java
> +        BigDecimal total = BigDecimal.ZERO;
I've double checked and solicitors costs are definitely always `'accepted'`. When they get duplicated as `HardshipDetails` the field is always marked as `'Y'`. I think the `x_calc_hardship_for_detail` procedure is designed to be generic, but in reality, the only variations that exist are around solicitors costs and if more variations are added in the future, we still check whether they're marked as accepted for other detail types.

2023-09-15 09:14 UTC, venkat980 approved these changes

2023-09-15 09:22 UTC, merged