WIP: LCAM 1008 & 1009 Refactor Hardship Detail Enums
ministryofjustice/laa-crime-hardship pull request #52
Opened 2023-10-26 11:09 UTC by nigelpain

## What

[Link to story LCAM1008](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1008)
[Link to story LCAM1009](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1009)

- Amended HardshipReviewDetailReason and HardshipReviewDetailCode enums to remove redundant type property
- Added missing 'Allowable Expense' value to HardshipReviewDetailReason enum

## Checklist

Before you ask people to review this PR:

- [ ] Tests should be passing: `./gradlew test`
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase main`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

2023-10-30 12:05 UTC, Mhowell494 commented on crime-hardship/src/main/java/uk/gov/justice/laa/crime/hardship/staticdata/enums/HardshipReviewDetailReason.java
>      @JsonValue
I think this can be safely removed at this point as there is now only a single field.

2023-10-30 12:15 UTC, Mhowell494 requested changes
I think we should take the opportunity to clean up the `@JsonValue` annotation in the `DetailReason` enum. There's also the `ExtraExpenditureDetailCode` enum, which largely mirrors the `DetailCode` enum and I think we should clean this up too. In retrospect, I should have included this in the ticket. This only appears in the Hardship service, so no need for additional changes in the Court Data API.

2023-10-31 08:48 UTC, nigelpain commented on crime-hardship/src/main/java/uk/gov/justice/laa/crime/hardship/staticdata/enums/HardshipReviewDetailReason.java
>      @JsonValue
Tried taking this out but getting an error calling off to MAAT API when requesting any hardship review with a detail reason, seems like it's still having trouble deserialising without the `@Jsonvalue ` assume possibly either due to reason containing spaces, or that it's in sentences case rather than all upper case 🤔 Are you happy to just leave the annotation in there?

2023-10-31 15:46 UTC, Mhowell494 commented on crime-hardship/src/main/java/uk/gov/justice/laa/crime/hardship/staticdata/enums/HardshipReviewDetailReason.java
>      @JsonValue
Yeah, that's fine, if it's causing issues then leave it in :)

2023-10-31 15:47 UTC, Mhowell494 approved these changes

2023-10-31 16:15 UTC, merged