LCAM-1149
ministryofjustice/laa-crime-hardship pull request #63
Opened 2024-01-08 12:42 UTC by Mhowell494

## What

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1149)

- Centralise all hardship validation checks within the service, including those currently in the Court Data API (these existing checks will be removed as part of a future ticket).
- Optimised existing validation checks and improved identifiers & package structure.
- Missing Spring boot configuration processor dependency added to `build.gradle`. This resolves several warnings in the `application.yaml` configuration files.
- Unit & integration test scenarios added for newly introduced validation checks.
- Updated required fields in `apiCalculateHardshipRequest` schema, allowing a validation check to be removed.

2024-01-10 09:56 UTC, venkat980 requested changes

2024-01-10 09:56 UTC, venkat980 commented on crime-hardship/src/main/java/uk/gov/justice/laa/crime/hardship/validation/HardshipValidationService.java
> +                || financialAssessment.getReplaced().equals("Y")
Its good practice to compare constants against variable.
"Y".equals(financialAssessment.getReplaced())

2024-01-10 09:56 UTC, venkat980 commented on crime-hardship/src/main/java/uk/gov/justice/laa/crime/hardship/service/MaatCourtDataService.java
> +
Should we pass the FinancialAssessmentDTO on the request to avoid DB call here?

2024-01-10 12:34 UTC, Mhowell494 commented on crime-hardship/src/main/java/uk/gov/justice/laa/crime/hardship/service/MaatCourtDataService.java
> +
I think this would be problematic because the Hardship service uses it's own schema and I don't really want to pollute that with data structures from MAAT.

2024-01-10 14:41 UTC, nigelpain commented on crime-hardship/src/main/java/uk/gov/justice/laa/crime/hardship/controller/HardshipController.java
> +
I assume that the hardship review date no longer needs validating on this endpoint and this isn't an accidental omission?

2024-01-11 17:58 UTC, venkat980 approved these changes

2024-01-12 10:45 UTC, merged